name: CI/CD for production

on: push

jobs:
  deployment:
    name: Library test by self-hosting
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: AWS SSM Send Command
        uses: ./dist
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secrets.INSTANCE_ID }}
          comment: aws-ssm-send-command testing
          working-directory: /home/ubuntu/
          command: echo $(date) >> logs.txt
